### ISSUE TITLE
Including a binary file

### ISSUE THREAD

**Issue by talolard** [FidelLimited/serverless-plugin-optimize#13]
Hey, 
Thanks for the awesome plugin. Some of my functions require a binary (ffmpeg). How can I set browserify to package the binary for some functions and not others? 
Thanks!

**Comment by goncaloneves** [comment]
Thanks Terry! ;)

Right now the way Browserify bundles is recursevily adding Commonjs
`requires`. For this reason in your situation if you are not directly
requiring anywhere in your code it just doesn't add.

What needs to be done is adding support for Browserify require method that
you can define a collection of modules outside the scope of your source
code.

We could do this in a way it can be added globally or by function.

I am off for two weeks from today. When I get back I can do a pull request
on this.

**Comment by goncaloneves** [comment]
Another reason, may be the extensions support. Another config setting.

It only bundles json and js files right now. This should be it.

Basically bringing support for these two will solve your issue.

**Comment by dionysio** [comment]
hey @goncaloneves, I am not quite sure I follow. Could you give an example of how you would include a binary to the package?

**Comment by goncaloneves** [comment]
I thought that you could use extensions as a way to do that.

I need to have some time to run that scenario. You want to include a binary
inside your bundle folder? Are you running in your code?

**Comment by dionysio** [comment]
Currently I have a function that starts new process with child_process.exec and it is just a binary stored in the same folder as the function.

ffmpeg is a good example for such use-case as OP pointed out.

**Comment by goncaloneves** [comment]
I understand now what it is. Files outside requires (Browserify bundle).

Solution is new PR that adds an include array option with file paths to be
included in the prefix folder and keep the same relative path structure.

Hopefully people write relative file paths in their code, otherwise it
won't find the file and will fail.

**Comment by goncaloneves** [comment]
@dionysio Can you test new release with includePaths?

**Comment by dionysio** [comment]
@goncaloneves works great! Thank you for your effort :+1:

**Comment by goncaloneves** [comment]
Perfect! 🙏

GL in your work.
