### ISSUE TITLE
Optimizer not firing before packaging when using 'deploy function' in Serverless v1.2.1

### ISSUE THREAD

**Issue by jeremydaly** [FidelLimited/serverless-plugin-optimize#23]
When trying to deploy a function using: `sls deploy function -f functionName`, the optimizer doesn't run until **AFTER** the function is packaged. This appears to be due to a change in the lifecycle events in v1.2.1 of Serverless.

I was able to fix this by updating the Serverless hooks to:
```
    /** Serverless hooks */
    this.hooks = {
      'after:deploy:createDeploymentArtifacts': this.afterCreateDeploymentArtifacts.bind(this),
      'before:deploy:createDeploymentArtifacts': this.beforeCreateDeploymentArtifacts.bind(this),
      'before:deploy:function:packageFunction': this.beforeCreateDeploymentArtifacts.bind(this),
      'after:deploy:function:packageFunction': this.afterCreateDeploymentArtifacts.bind(this)
    }
```

**Comment by goncaloneves** [comment]
Hi Jeremy,

Thanks for reporting this.

I did a release today that should fix that on 1.2.x but I am hooking to
initialize. Makes a lot more sense to use packageFunction hook.

I am closing tomorrow several open issues and I will refactor to that hook.
