### ISSUE TITLE
__dirname references 

### ISSUE THREAD

**Issue by vanerleo** [FidelLimited/serverless-plugin-optimize#28]
after optimization, all references to __dirname pointing to path on local machine.

eg project structure:
```
/Users/test-user/project/
                                          - bin/
                                                    someFile.bin
                                          - lambda-run-this.js
```

using default configs of the plug-in
when deploying to lambda
the structure inside zip becomes
```
_​optimize​/project-name-lambda-run-this/lambda-run-this.js
```

in `lambda-run-this.js` when referencing `__dirname + '/bin/someFile.bin'` , for some reason it would return `/Users/test-user/project/bin/someFile.bin` , as in the path on my local machine and not the path on lambda ie `/var/task/_​optimize​/project-name-lambda-run-this/bin/someFile.bin`

somehow `__dirname` gets backed in during the optimisation.

**Comment by goncaloneves** [comment]
This has been discussed in https://github.com/FidelLimited/serverless-plugin-optimize/issues/13.

You need to use relative paths in your code for it reference the files correctly after bundling to prefix folder. In that example case: `'./bin/someFile.bin'`.
