### ISSUE TITLE
Run a function locally

### ISSUE THREAD

**Issue by Bill-Niz** [FidelLimited/serverless-plugin-optimize#30]
Is there a way to run optimize lambda local ?

**Comment by goncaloneves** [comment]
You can run by using `sls deploy --noDeploy`.

Now what you can't do is run with serverless-offline and this is a cool feature to have. Hooking to serverless-offline events and transforming all handlers paths to the bundles.

Having this, any possible errors after bundling would be caught locally avoiding broken deployments.

**Comment by goncaloneves** [comment]
Continue sls-offline conversation in #31 . Closing this one.
