### ISSUE TITLE
Support for ES6 and NodeJS 6.10

### ISSUE THREAD

**Issue by soda0289** [FidelLimited/serverless-plugin-optimize#36]
With AWS Lambda adding support for NodeJS 6.10 uglify needs to be updated to support es6 features.

Currently there is this fork: https://github.com/mishoo/UglifyJS2 that should allow for es6 to be compiled and used with this plugin. I will do some testing to make sure everything works as expected. The other alternative is to compile the code down to es5.

Would this project consider upgrading to uglifyjs2?

**Comment by soda0289** [comment]
We would need to use the harmony branch as es6 support has not been merged in to uglifyjs2 yet

**Comment by soda0289** [comment]
If i disable minify it works. It looks like we would need uglifyify to upgrade to the harmony branch and not this project. I will open an issue there.

**Comment by goncaloneves** [comment]
@soda0289 certainly now we don't need to use Babel `es2015` preset and instead a lighter preset like [babel-preset-node6](https://github.com/Salakar/babel-preset-node6).

The only thing that should break is Uglify. For that [harmony](https://github.com/mishoo/UglifyJS2/tree/harmony#harmony) branch must be used.

**Comment by goncaloneves** [comment]
@soda0289 Uglifyify uses main Uglify branch, so it would require fork to change branch to harmony.

**Comment by goncaloneves** [comment]
As soon as https://github.com/mishoo/UglifyJS2/issues/448 is closed and harmony is merged I will move forward with this change.

For now if you want to bundle node6.10 compatible ES6, just set `minify: false` and use `babel-preset-node6` and it works fine.

**Comment by antonioasmoura** [comment]
Including local invoke ? Using this preset i can't invoke locally. I get error on 'import' modules.

**Comment by soda0289** [comment]
@antonioasmoura Have you updated serverless? They mention a fix for local invoke in one of thier newer releases.
https://github.com/serverless/serverless/releases/tag/v1.10.0

**Comment by antonioasmoura** [comment]
@soda0289 I'm using 1.10.2 version and I still getting error.

`import { knex } from 'knex';
^^^^^^
SyntaxError: Unexpected token import`

**Comment by goncaloneves** [comment]
@antonioasmoura Local invoke doesn't run optimize and `import` statement isn't yet supported by Node. You could use `serverless-offline` for local invocation or just replace with `require`.

**Comment by goncaloneves** [comment]
Optimize is not being called during SLS `invoke:local` event because there is no reason to. `serverless-offline` and other plugins do a fantastic job of tackling this with a lot more functionality. The mission here is to optimize deployment artifacts. Hope this clears anything.

**Comment by bvalerius** [comment]
`serverless-offline` is for API gateway + Lambda. What if I am building services that are not invoked via API gateway? Testing locally is becoming an issue if I want to use this plugin with Babel.

**Comment by goncaloneves** [comment]
@bvalerius Well you need to work around the edges. You can use webpack plugin that has invoke implementation included.

**Comment by goncaloneves** [comment]
Again... PR's are welcomed 👈

**Comment by goncaloneves** [comment]
`invoke local` should be supported in the latest release.

@antonioasmoura @bvalerius take some minutes next time and help maintain this MIT licensed repo. Requests and issues are easy to open anywhere, finding and sharing solutions is where the true value is.

Reopening when UglifyJS2 #448 is closed.

**Comment by goncaloneves** [comment]
@soda0289 @antonioasmoura Removed UglifyJS2 and went with Babili. In the latest release, `babel-preset-env` will take care of transpiling to the right Node run time allowing Babili do it's magic.

I have done some initial tests and both optimization times and Lambda cold start have greatly improved with Node6.10 ES2015. 🚀

**Comment by soda0289** [comment]
@goncaloneves Thanks, will test this out tomorrow!

**Comment by antonioasmoura** [comment]
Thanks @goncaloneves ! 

I'm not an very experienced dev yet, so I really don't feel comfortable to do any PR atm, but when I become more ninja, it will be a pleasure help this repository!
