### ISSUE TITLE
Problem with 'knex' module

### ISSUE THREAD

**Issue by aasmoura** [FidelLimited/serverless-plugin-optimize#37]
Hey guys, I tried several different options with bundle/no bundle using 'external' option, etc and I can't make the 'knex' module works using serverless-plugin-optmize.

When function run and uses `require('knex') ` we got the following error:

`Cannot find module 'babel-runtime/core-js/object/define-properties'.`

Any help ?

**Comment by goncaloneves** [comment]
@aasmoura without requiring knex does it babelify and browserify succesfully?

**Comment by aasmoura** [comment]
Sorry, it was my mistake, I had an permission problem on the node_modules folder.

👍🏼

**Comment by suryacaprice** [comment]
i have the same issue how did you solve it?
