### ISSUE TITLE
does not run for google cloud functions

### ISSUE THREAD

**Issue by bryanvaz** [FidelLimited/serverless-plugin-optimize#51]
@goncaloneves , I'm trying to use optimize to transpile v8 code down to v6.11 for google cloud functions, however it doesn't seem to run. 

Is there a specific filter somewhere in the code 

To recreate, just use the google quickstart and add the plugin to the project, and call a local invoke (expected behavior is for sls to optimize first, create a minified version, then execute the optimized code).

**Comment by goncaloneves** [comment]
@bryanvaz it is related to #35.

That's why it says on the readme that is AWS provider only.

If anyone like you that has already the error in hands that could peak into this and contribute, my deepest thanks 👍  Knowing that for AWS it works very well 👌

**Comment by bryanvaz** [comment]
Ok let me pop the top off optimise this weekend and see where it hooks in. The logic should be the same as AWS. I'll shoot you a note if I can't find the AWS hook.

Cheers,
Bryan

On Oct 20, 2017, at 5:57 AM, Gonçalo Neves <notifications@github.com> wrote:

@bryanvaz it is related to #35.

That's why it says on the readme that is AWS provider only.

If anyone like you that has already the error in hands that could peak into this and contribute, my deepest thanks 👍 Knowing that for AWS it works very well 👌

**Comment by goncaloneves** [comment]
Hey @bryanvaz any update on this? 🤓

**Comment by ramonck** [comment]
+1
