### ISSUE TITLE
Error "Cannot find Module" no stack trace.

### ISSUE THREAD

**Issue by Neuroforge** [FidelLimited/serverless-plugin-optimize#57]
Hello,

I had an issue with my was lambda function. I have been following this tutorial - https://medium.com/@robdel12/using-amazon-lambda-to-create-a-contact-form-a41b192fae84

First the issue was the same as in https://github.com/serverless/serverless/issues/948 however after following those instructions  and running _npm install_ I now get the following error when testing.

> {"errorMessage":"Cannot find module '/var/task/handler'","errorType":"Error","stackTrace":[]}

Regards,

Daniel

**Comment by goncaloneves** [comment]
Did you find a solution to the issue?

**Comment by maazmk** [comment]
Any update on this?
