### ISSUE TITLE
Breaking envkey (TypeError: Cannot create property 'stack' on string 'ENVKEY invalid. Couldn't load vars.')

### ISSUE THREAD

**Issue by kvarela** [FidelLimited/serverless-plugin-optimize#61]
First of all, thank you for this plugin. It cut down my serverless bundle by about 30x.

However, my function no longer executes on AWS. It executes locally, but not in AWS, and seems to be something to do with [envkey](https://docs.envkey.com/integration-quickstart.html#envkey-node), but I'm not sure why it broke.

The error I'm seeing in the logs is:
```TypeError: Cannot create property 'stack' on string 'ENVKEY invalid. Couldn't load vars.'```

I've verified, however, that the ENVKEY environment variable is set and valid.

I'm importing `envkey` at the top of my handler file as instructed like:
```import 'envkey'```

Any ideas? Or config I need to set to make this work?

**Comment by goncaloneves** [comment]
Thanks man. Did you find a solution to this issue? Only fails in AWS?

**Comment by goncaloneves** [comment]
Closing this one and keeping conversation in one.
