### ISSUE TITLE
optimize incompatible with mysql2

### ISSUE THREAD

**Issue by eaglesphan50** [FidelLimited/serverless-plugin-optimize#62]
Using this serverless plugin is incompatible with the mysql2 node library. 

The optimizer fails to load all the files from the mysql2 directory. After several hours of debugging we found the problem stemmed from the way that mysql2 handled require statements. 
```
'auth_switch_request auth_switch_response auth_switch_request_more_data binlog_dump register_slave ssl_request handshake handshake_response query resultset_header column_definition text_row binary_row prepare_statement close_statement prepared_statement_header execute change_user'
  .split(' ')
  .forEach(function(name) {
    var ctor = require('./' + name + '.js');
    module.exports[ctor.name] = ctor;
    // monkey-patch it to include name if debug is on
    if (process.env.NODE_DEBUG) {
      if (ctor.prototype.toPacket) {
        var old = ctor.prototype.toPacket;
        ctor.prototype.toPacket = function() {
          var p = old.call(this);
          p._name = ctor.name;
          return p;
        };
      }
    }
  });
```
As you can see the require statements are being pieced together inside this for loop and optimize does not pick them up, leaving out the files. When we replaced this code with all the requires and exports written out, the function was optimized fine.
```
var temp = require('./auth_switch_request.js');
module.exports[temp.name] = temp;
temp = require('./auth_switch_response.js');
module.exports[temp.name] = temp;
temp = require('./auth_switch_request_more_data.js');
module.exports[temp.name] = temp;
temp = require('./register_slave.js');
module.exports[temp.name] = temp;
temp = require('./ssl_request.js');
module.exports[temp.name] = temp;
...
```

This isn't really a bug with the optimizer necessarily but I wanted to post this here in case anyone else had a similar problem where files were not being included by the optimizer.

If functionality could be implemented to see this type for require inside a loop, that would be very helpful though. :)

**Comment by selected-pixel-jameson** [comment]
@eaglesphan50 Did you ever figure out a solution for this??
