### ISSUE TITLE
No need to exclude aws-sdk by default

### ISSUE THREAD

**Issue by skilledDeveloper** [FidelLimited/serverless-plugin-optimize#8]
Since `aws-sdk` has recently supported `browserify`, it might be the time to stop excluding it in this plugin.
More info: https://github.com/aws/aws-sdk-js/issues/696

**Comment by goncaloneves** [comment]
@skilledDeveloper Thanks for bringing this.

From what I read Browserify support is to `require` individual modules like `require('aws-sdk/clients/s3')` if you want to use the latest sdk version and not the lambda one.
If this is so, it will depend on the setup and preference. Not having it as default, would require to always setting it up globally and probably this is the majority use case.

Right now we could remove `aws-sdk` from `exclude` by setting globally in `custom` or if we use the functions exclude:
```yml
custom:
  optimize:
    exclude: []
```
