### ISSUE TITLE
optimize plugin not include some packages?

### ISSUE THREAD

**Issue by kop7** [FidelLimited/serverless-plugin-optimize#87]
I have problem with serverless optimize plugin, 

`"errorMessage":"package.json does not exist at /var/task/_optimize/xxx/src/.build/node_modules/bcrypt/package.json"`

Whay optimize plugin not include this package??

But when I remove optimize plugin, work fine....

**Comment by ValiDraganescu** [comment]
You need to add json in the extensions

`custom:
  optimize:
    extensions: ['.json']`
